### ISSUE TITLE
Improve /meta/ API

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrest#8]
The current `/meta/` API in catalogs has many warts that should be removed.
- [x] It exposes a horrible JSON serialization of a key-value store, using JSON objects like: `[{"k": "keyname", "v": "value1"}, {"k": "keyname", "v": "value2"}]` instead of normal JSON idioms like `{"keyname": ["value1", "value2"]}`.
- [x] It returns `204 No Content` instead of `404 Not Found` for operations on specific entries which are not present e.g. GET or DELETE on `/catalog/1/meta/unknown_acl` or `/catalog/1/meta/read_user/unknown_user`.
- [ ] It returns `404 Not Found` instead of `409 Conflict` when trying to access ACL resources on an unknown catalog. This means a programmatic client cannot easily determine whether an ACL entry is missing or a more basic problem has occurred with the whole catalog ID reference.
- [ ] It only supports PUT and DELETE on specific entries with no option to set a whole ACL at once by sending an appropriate JSON representation for  the ACL-level resource.
- [ ] It has no built-in notion of which keys are meaningful, to prevent the client from setting useless ACLs. I think a particular release of the code should not allow meaningless metadata keys to be set by REST clients (though it should tolerate existing entries in the catalog metadata, e.g. if the set of supported keys has changed through software updates on an existing catalog).

**Comment by robes** [comment]
should we keep the resource named as `/meta/` or change to some other name for it. I.e., `prop` or `properties`.

**Comment by robes** [comment]
Actually, should we just change this to the `catalog/N/acl` container resource? So far `meta` is really just a container resource for ACLs. We haven't put anything else there and its not clear we should put ACLs under a resource for "properties" or "metadata". Also, if we change this to `acl`, then it could be consistent in the future if we support fine grain `acl` resources. E.g., `catalog/N/schema/X/table/Y/acl`.

If we agree, then I would also propose to drop the `meta` resource.

**Comment by karlcz** [comment]
We could also collapse a whole level and just make it something like
/catalog/N/readers (e.g. to fetch one ACL) or
/catalog/N/readers/member (e.g. to delete one member).

We're only going to have a finite set of ACL names and we know they're
not going to collide with existing APIs like /schema, /entity, etc.

The only reason for an /acl/ parent would be to allow all ACLs to be
fetched at once.  We could just as easily make them fields in the
catalog representation, served at /catalog/N.

**Comment by robes** [comment]
I like that suggestion.

**Comment by karlcz** [comment]
This is partially addressed in 255ea0f5184d04a47062c23a6411c88b491b1918 which simplifies the serialization and the basic per-entry CRUD API rules.

**Comment by karlcz** [comment]
I think this should be absorbed into #118 and probably introduce an `acl/` tree on catalogs with revised structure so it can be a consistent API up and down the model hierarchy.
